name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npm run prettier

      - name: commitlint
        run: npm run commitlint

      - name: Test build
        run: npm test
